---
---

```{r setup, include=FALSE}
set.seed(80085)
knitr::opts_chunk$set(echo = F)

# =============================================================================
# Libraries
# =============================================================================
libraries <- c("cowplot","tidyverse","ggthemes")

lapply(libraries, function(x) {
    if(!require(x, character.only = T, quietly = T)) {
      install.packages(x)
      require(x, character.only = T)
    }
  }
)

theme_set(theme_minimal(10))

scale_color_discrete <- function(...) {
  scale_color_colorblind(...)
}
scale_fill_discrete <- function(...) {
  scale_fill_colorblind(...)
}

# =============================================================================
# Functions
# =============================================================================
# Where is this script?
Where_Am_I <- function(path=T){
  if (path == T){
    dirname(rstudioapi::getSourceEditorContext()$path)
  }
  else {
    rstudioapi::getSourceEditorContext()$path
  }
}

## Read basic functions
## Dentro de MyFuns.R est?n los paquetes que estamos cargando.
load_Funs <- function(){
  id_computer = Sys.info()[[4]]
  funs_path = ifelse(id_computer ==  "ID53543",
                     'C:/Users/borja.aguado/Dropbox/Funs.R',
                     ifelse(id_computer == "DESKTOP-UJ1UCTV",
                            'C:/Users/santa/Dropbox/Funs.R',
                            "Funs.R"))
  source(funs_path)
}

load_Funs()
```

```{r, fig.width=7,eval = F , include = F }
set.seed(1)
DT = 0.01
kk <- list()
it = 1

for (r in 0.12){
#for (r in c(0.033,0.11)){
  for (z in seq(10,50,by=5)){
    for (i in 1:20){
      kk[[it]] <- expand.grid(Xi=0, Yi= 0, Zi = z,
                              Xf = 0, Yf = 0, Zf = 0,
                              t = seq(0,1.5,by=DT), TTC = 1.5, G = 9.807, dt = DT, radius = r) %>%
        mutate(vx = (Xf-Xi)/max(t), vy = max(t)*G/2, vz = (Zf-Zi)/max(t),
               ball_x = Xi + vx*t,
               ball_y = Yi + vy*t - 0.5 * t * t * 9.807,
               ball_z = Zi + vz*t,
               d = eudist_3d(0,ball_x,0,ball_y,0,ball_z),
               theta = atan(radius/d) * 2,
               theta_dot = c(NA,diff(theta))/dt,
               # My solution (account for deviations from WF at low thetas)
               theta = theta + rnorm(n(),sd=log(theta+1)*0.04),
               theta_dot = theta_dot + rnorm(n(),sd=log(theta_dot+1)*0.1),
               tau = theta/theta_dot,
               #theta = atan(radius/d) * 2,
               #theta_dot = c(NA,diff(theta))/dt,
               size = radius * 2,
               #G = G + rnorm(n(),sd=G*0.05),
               beta = beta(a = eudist_2d(ball_x,0,ball_z,0),
                           b = eudist_2d(ball_x,Xi,ball_z,Zi),
                           c = eudist_2d(0,Xi,0,Zi)),
               betadot = c(NA,diff(beta))/dt,
               beta = beta + rnorm(n(),sd=beta*0.05),
               betadot = betadot + rnorm(n(),sd=betadot*0.05),
               gamma = asin(ball_y/d),
               gammadot = c(NA,diff(gamma))/dt,
               gamma = gamma + rnorm(n(),sd=gamma*0.05),
               gammadot = gammadot + rnorm(n(),sd=gammadot*0.05),
               tc1 = ((2*size*gammadot)/(G*theta*cos(abs(gamma)))),
               rt = TTC - t,
               i = i)
      it = it + 1
    }
  }
}



kk_t <- bind_rows(kk)

kk2 <-  kk_t %>%
  group_by(t,Zi,rt,radius) %>%
  summarize(sd_tau = sd(tau,na.rm=T),
            tau = mean(tau,na.rm=T, trim = 0.01),
            sd_tc1 = sd(tc1, na.rm = T),
            tc1 = mean(tc1, na.rm=T,trim = 0.01),#,
            wf_tau = sd_tau/tau,
            wf_tc1 = sd_tc1/tc1
            )



lb <- c(0.01, 0.02,0.04, 0.1,0.2, 0.5, 1.50)

Sim_TTC <- plot_grid(
  plot_grid(
    ggplot() +
      labs(title = expression(tau~model)),
    plot_grid(
      ggplot(kk_t %>% filter(i == 1),aes(rt,tau,group=Zi,color=Zi)) +
        xlab("Remaining Time") +
        ylab(expression(paste(tau,"  (s)")))  +
        geom_hline(yintercept=0.01) +
        scale_x_reverse()+
        geom_vline(xintercept=0.2)+
        geom_line(size=1) +
        geom_abline(aes(intercept=0, slope=-1),linetype=2)  +
        scale_colour_continuous(name="Vx",low="red", high="green"),
      ggplot(kk2,aes(rt,wf_tau,group=Zi,color=Zi)) +
        xlab("Remaining Time") +
        ylab(expression(paste("WF ",tau," model  (s)")))  +
        geom_hline(yintercept=c(0.01,0.1)) +
        scale_x_reverse()+
        geom_vline(xintercept=0.2)+
        geom_line(size=1) +
        #geom_abline(aes(intercept=0, slope=-1),linetype=2)  +
        scale_x_continuous(trans=reverselog_trans(),breaks = lb, labels = lb) +
        scale_y_continuous(trans=log_trans(),breaks = lb, labels = lb) +
        scale_colour_continuous(name="Vx",low="red", high="green")
    ), nrow = 2, rel_heights = c(0.1,0.9)
  ),

  plot_grid(
    ggplot() +
      labs(title = expression(GS~model)),
    plot_grid(
      ggplot(kk_t %>% filter(i == 1),aes(rt,tc1,group=Zi,color=Zi)) +
        xlab("Remaining Time") +
        ylab(expression(paste("GS model  (s)")))  +
        geom_hline(yintercept=0.01) + scale_x_reverse()+ geom_vline(xintercept=0.2)+
        geom_line(size=1) +
        geom_abline(aes(intercept=0, slope=-1),linetype=2)  +
        scale_colour_continuous(name="Vx",low="red", high="green"),
      ggplot(kk2,aes(rt,wf_tc1,group=Zi,color=Zi)) +
        xlab("Remaining Time") +
        ylab(expression(paste("WF GS model  (s)")))  +
        geom_hline(yintercept=c(0.01,0.06)) +
        scale_x_reverse()+
        geom_vline(xintercept=0.2)+
        geom_line(size=1) +
        #geom_abline(aes(intercept=0, slope=-1),linetype=2)  +
        scale_x_continuous(trans=reverselog_trans(),breaks = lb, labels = lb) +
        scale_y_continuous(trans=log_trans(),breaks = seq(0,0.1,by=0.02), labels = seq(0,0.1,by=0.02)) +
        scale_colour_continuous(name="Vx",low="red", high="green")
    ), nrow = 2, rel_heights = c(0.1,0.9)
  ),nrow = 2
)

save(Sim_TTC, file = "Sim_TTC.RData")
```

## Estimaciones de TTC

¿Qué modelo es más exacto y preciso?

```{r}
load("Sim_TTC.RData")
Sim_TTC
```

  - Ambos modelos, GS y $\tau$, son muy exactos.
  
  - La Weber Fraction del modelo GS es aproximadamente 0.06 durante toda la trayectoria. En el modelo $\tau$ es superior a 0.1 durante la mayor parte de la trayectoria. Sin embargo converge a 0.1 al final de la trayectoria, es decir, 200 ms. antes de la colisión. 
  
  

